apiVersion: redhatcop.redhat.io/v1alpha1
kind: GroupSync
metadata:
  name: github-groupsync
  namespace: group-sync-operator
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "5"
spec:
  providers:
    - name: github
      github:
        organization: mbach04
        credentialsSecret:
          name: github
          namespace: group-sync-operator
  schedule: "0 * * * *"
